"""Add task audit logging

Revision ID: 1163e37201e3
Revises: 4ebfdcfafd20
Create Date: 2026-02-22 02:36:08.247049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1163e37201e3'
down_revision = '4ebfdcfafd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_audit')
    # ### end Alembic commands ###
