"""Add assigned_to to tasks

Revision ID: 48063e17bcd3
Revises: d2f172b113f5
Create Date: 2026-02-15 19:41:01.474970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48063e17bcd3'
down_revision = 'd2f172b113f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
